-- Script generated by bopbunsKG#9756
-- Execute the script when the shop opens

local args = {
    [1] = {
        [1] = "M249"
    }
}

game:GetService("ReplicatedStorage").Bricks.PreRunShop:FireServer(unpack(args))